### PR TITLE
add directory index file support

### PR DESCRIPTION
**Pull request by aaronmccall**
Copied the logic from connect's static middleware which appends 'index.html', if the final character of the file name is '/'.

### CODE REVIEW

**Comment by tomgco** [comment]
If you could provide a test for this I would be happy to pull this in, however If you have problems with the tests let me know and we can sort something out!

**Comment by aaronmccall** [comment]
I'll add a test ASAP. I'm planning on using gzippo in a production site once this feature is merged.

**Comment by aaronmccall** [comment]
@tomgco all the tests are failing with "Error: Response not completed"

Any idea as to why?

**Comment by aaronmccall** [comment]
@tomgco nevermind. It worked after I deleted connect from the node_modules dir. 

FYI: The tests don't run properly for me with connect@2.3.3 installed.

**Comment by aaronmccall** [comment]
Rebased against your master and verified that tests do pass with Connect 1.9.0 installed.

**Comment by tomgco** [comment]
This can now be found in 0.1.7, Thanks!

**Pull request merged**
